### ISSUE TITLE
Deployment Issue with Upstream dependency differences

### ISSUE THREAD

**Issue by Mufc2202** [MoscatelliMarco/medusa-plugin-blog#3]
#10 6.246 npm ERR! ERESOLVE unable to resolve dependency tree
#10 6.246 npm ERR!
#10 6.246 npm ERR! While resolving: medusa-starter-default@0.0.1
#10 6.246 npm ERR! Found: react@18.2.0
#10 6.246 npm ERR! node_modules/react
#10 6.246 npm ERR!   peer react@"18.2.0" from medusa-plugin-blogger@0.0.1
#10 6.246 npm ERR!   node_modules/medusa-plugin-blogger
#10 6.246 npm ERR!     medusa-plugin-blogger@"^0.0.1" from the root project
#10 6.246 npm ERR!   peer react@">=16.8" from react-router-dom@6.22.3
#10 6.246 npm ERR!   node_modules/react-router-dom
#10 6.246 npm ERR!     peer react-router-dom@"6.22.3" from medusa-plugin-blogger@0.0.1
#10 6.246 npm ERR!     node_modules/medusa-plugin-blogger
#10 6.246 npm ERR!       medusa-plugin-blogger@"^0.0.1" from the root project

#10 6.246 npm ERR!
#10 6.246 npm ERR! Could not resolve dependency:
#10 6.246 npm ERR! peer react@"^18.3.1" from react-dom@18.3.1
#10 6.246 npm ERR! node_modules/react-dom
#10 6.246 npm ERR!   peer react-dom@">=16.8" from react-router-dom@6.22.3
#10 6.246 npm ERR!   node_modules/react-router-dom
#10 6.246 npm ERR!     peer react-router-dom@"6.22.3" from medusa-plugin-blogger@0.0.1
#10 6.246 npm ERR!     node_modules/medusa-plugin-blogger

#10 6.246 npm ERR!       medusa-plugin-blogger@"^0.0.1" from the root project
#10 6.246 npm ERR!
#10 6.246 npm ERR! Fix the upstream dependency conflict, or retry
#10 6.246 npm ERR! this command with --force or --legacy-peer-deps
#10 6.246 npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
#10 6.246 npm ERR!

#10 6.248 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-06-19T21_49_30_558Z-debug-0.log
#10 ERROR: process "/bin/bash -ol pipefail -c npm i" did not complete successfully: exit code: 1

Deploying on Railway and am not sure the exact dependency issue. Any ideas?

**Comment by MoscatelliMarco** [comment]
The error you're seeing (ERESOLVE unable to resolve dependency tree) occurs when npm detects a conflict in your project's dependency versions. In this case, the issue is related to different versions of react and react-dom. The medusa-plugin-blogger package requires a compatible version of React. Since it lists a peer dependency for React as 18.2.0, but react-dom requires a higher version (18.3.1), this creates a conflict. Upgrade your react-dom version and you should not find this problem.
